version: "3.9"
services:
  paczkomex:
    container_name: paczkomex
    build:
      context: paczkomex
      dockerfile: Dockerfile
    image: paczkomex:latest
    environment:
      - SPRING_PROFILES_ACTIVE=local
    ports:
      - 8080:8080
    networks:
      - network

networks:
  network:
    driver: bridge
