version: "3.9"
services:
  paczkomex:
    container_name: paczkomex
    build:
      context: paczkomex
      dockerfile: Dockerfile
    image: paczkomex:latest
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/paczkomex
    ports:
      - 8080:8080
    networks:
      - network
    depends_on:
      - db
  db:
    image: postgres:15.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=paczkomex
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - network
    healthcheck:
      test: pg_isready -U postgres
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  network:
    driver: bridge

volumes:
  db:
    driver: local