logging:
  level:
    pamiw.paczkomex: DEBUG

---

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/paczkomex
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL81Dialect
    hibernate:
      ddl-auto: update # (create, create-drop, validate, update)

---

spring:
  config:
    activate:
      on-profile: local

  h2:
    console.enabled: true # http://localhost:8080/h2-console
    console.settings.web-allow-others: true
  datasource:
    url: jdbc:h2:mem:db
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect